### ISSUE TITLE
ModuleNotFoundError when triggering the notebook test locally using nutter

### ISSUE THREAD

**Issue by Ziyu-Chen** [mingxiang-isao/dbx-unit-tests#1]
The following error appeared when I triggered the notebook test locally using nutter.
```
Notebook output: ModuleNotFoundError: No module named 'runtime'
```
https://github.com/mingxiang-isao/dbx-unit-tests/blob/19264a3bbabfb45d87c3214a9460ac05d157a618/project/tests/notebooks/test_all.py#L13

I solved it by adding the following command to the beginning of test_all.py. 
```
%pip install nutter
```

**Comment by Ziyu-Chen** [comment]
Actually, I found a better way to fix this error [here](https://github.com/microsoft/nutter).

Apparently, packages can be installed via PyPI in a cluster.

It would be nice if you could include this in README.md.

**Comment by mingxiang-colorkrew** [comment]
Oh right, I followed the Nutter documentation to add it to the cluster, but forgot to add it to the README. Thanks for catching this!
